version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
  
  pre_build:
    commands:
      - echo "Running tests..."
      - npm test
  
  build:
    commands:
      - echo "Packaging Lambda function..."
      - zip -r deployment.zip . -x "*.git*" "node_modules/aws-sdk/*"
  
  post_build:
    commands:
      - echo "Build completed!"

artifacts:
  files:
    - deployment.zip
    - appspec.yml
