version: 0.2

phases: 
  install:
    runtime-versions:
      nodejs: 20  
    commands:
      - echo "Installing dependencies..."
      - npm ci  # Install packages from package-lock.json
  
  pre_build:
    commands: 
      - echo "Running tests..."
      - npm test  # This runs test script
  
  build:
    commands:
      - echo "Build phase - preparing deployment package"
      - echo "Listing files:"
      - ls -la
  
  post_build:
    commands:
      - echo "Build completed successfully!"

# Package everything for Lambda deployment
artifacts:
  files:
    - '**/*'
  name: BuildArtifact
